### ISSUE TITLE
Publish to hex.pm

### ISSUE THREAD

**Issue by aberman** [snaiper80/hashids-erlang#2]
Hi,

I was hoping you could publish this library to Hex. (https://hex.pm)

Thanks!

**Comment by snaiper80** [comment]
@aberman Thanks for your proposal. I will do it until this weekend.

**Comment by snaiper80** [comment]
@aberman You can find this in hex.pm link: https://hex.pm/packages/hashids_erlang 
Because of hashids-elixir port, this library's name is 'hashids_erlang'.

**Comment by aberman** [comment]
Awesome!  Thank you!
